server:
  forward-headers-strategy: framework
  servlet:
    context-path: /remote-ops/server-core/
spring:
  application:
    name: server-core
  config:
    import: optional:file:.env[.properties]

remote-ops:
  commands:
    - messages:
        - "перезагрузить ${name}"
        - "перезагрузи ${name}"
      command: "reboot"
    - messages:
        - "выключить ${name}"
        - "выключи ${name}"
      command: "shutdown"