server:
  forward-headers-strategy: framework
spring:
  application:
    name: server-core
  config:
    import: optional:file:.env[.properties]
feign:
  clients:
    main:
      url: ${CLIENT_MAIN_URL}