services:
  server-core:
    image: server-core:latest
    build: server-core
    restart: "no"
    ports:
      - "8184:8080"
    environment:
      - CLIENT_MAIN_URL=http://192.168.0.124:7000
  client-node:
    image: client-node:latest
    build: client-node
    restart: "no"
    ports:
      - "7000:7000"