services:
  server-core:
    image: server-core:latest
    build: server-core
    restart: "no"
    ports:
      - "8184:8080"
  client-node:
    image: client-node:latest
    build: client-node
    restart: "no"
    ports:
      - "7000:7000"
  skill:
    image: skill:latest
    build: skill
    restart: "no"
    ports:
      - "8186:8080"