[windows.post]
shutdown = "shutdown /s /t 1"
reboot = "shutdown /r /t 1"
sleep = "shutdown /h"
play = "nircmd.exe mediaplay"
pause = "nircmd.exe mediapause"
play_pause_toggle = "nircmd.exe sendkey 0xB3 press"
volume_up = "nircmd.exe changesysvolume 5000"
volume_down = "nircmd.exe changesysvolume -5000"
next_track = "nircmd.exe sendkey 0xB0 press"
prev_track = "nircmd.exe sendkey 0xB1 press"

[macos.post]
shutdown = "sudo shutdown -h now"
reboot = "sudo shutdown -r now"
sleep = "pmset sleepnow"
play = "osascript -e 'tell application \"Music\" to play'"
pause = "osascript -e 'tell application \"Music\" to pause'"
play_pause_toggle = "osascript -e 'tell application \"Music\" to playpause'"
volume_up = "osascript -e 'set volume output volume ((output volume of (get volume settings)) + 5)'"
volume_down = "osascript -e 'set volume output volume ((output volume of (get volume settings)) - 5)'"
next_track = "osascript -e 'tell application \"Music\" to next track'"
prev_track = "osascript -e 'tell application \"Music\" to previous track'"

[linux.post]
shutdown = "sudo shutdown -h now"
reboot = "sudo reboot"
sleep = "systemctl suspend"
play = "playerctl play"
pause = "playerctl pause"
play_pause_toggle = "playerctl play-pause"
volume_up = "amixer -D pulse sset Master 5%+"
volume_down = "amixer -D pulse sset Master 5%-"
next_track = "playerctl next"
prev_track = "playerctl previous"