[windows.post]
shutdown = "shutdown /s /t 1"
reboot = "shutdown /r /t 1"
sleep = "shutdown /h"

[macos.post]
shutdown = "sudo shutdown -h now"
reboot = "sudo shutdown -r now"
sleep = "pmset sleepnow"

[linux.post]
shutdown = "sudo shutdown -h now"
reboot = "sudo reboot"
sleep = "systemctl suspend"
